### ISSUE TITLE
Vulnerabilities in td-agent 4.5.2-1

### ISSUE THREAD

**Issue by paragsn** [fluent/fluent-package-builder#740]
We are installing td-agent via apt on ubuntu
Latest available on apt is 

```
# apt-cache policy td-agent
td-agent:
  Installed: 4.5.2-1
  Candidate: 4.5.2-1

```

Does these CVEs effect td-agent

These are from **rexml** package

CVE-2024-41123
CVE-2024-41946
CVE-2024-49761

Are any latest releases planned ?
